db.getCollection('group_types').aggregate(
[{
    $match: {
        $or:[
                {name: "Country"},
                {name: "Countries"},
                {name: "Region"},
                {name: /ountr/}, 
                {locked_as: "location"},
                {name: "Location"},
                {name: "Locations"},
                
        ]}
}, {
    $lookup: {
        from: 'companies',
        localField: 'company_id',
        foreignField: '_id',
        as: 'companies'
    }
}, {
    $match: {
        "companies.status": "active",
        "companies.subdomain": {$in:[ //replace these subdomains for other Cohorts
            "dal-tile",
            "kronos",
            "fanatics",
            "icare",
            "merkleproud",
            "etrade",
            "meredith",
            "wirelessvision",
            "spark",
            "goodwillaz",
            "autismlearningpartners",
            "medlinerewards",
            "clearesult",
            "kaiser",
            "turnerprops",
            "vonageapplause",
            "mtc",
            "powerschool",
            "infogroup",
            "legoland",
            "medidatashyft",
            "vertafore",
            "azblue",
            "fbfs",
            "tshc",
            "chimesolutions",
            "directtravel",
            "cheers",
            "mykazoo",
            "borregohealth",
            "bravo",
            "khoros",
            "kudos",
            "motoristsgroup",
            "q2",
            "eplus",
            "mvp",
            "tbkbank",
            "accruent",
            "distributionintl",
            "renaissance",
            "canterburypark",
            "mood",
            "dealersocket",
            "braunability",
            "bvs",
            "centralsquare",
            "kia",
            "jbhunt",
            "interimhealthcare",
            "flexential",
            "topguardinc",
            "selectquote",
            "coresource",
            "maxor",
            "blackline",
            "smsassist",
            "dfs",
            "intermed",
            "habitat",
            "abaco",
            "cws",
            "evergreen",
            "jjtaylor",
            "omnitrax",
            "pall",
            "partyrentalltd",
            "ultimusfundsolutions",
            "tracintermodal",
            "bungie",
            "channeladvisor",
            "emmaus",
            "stimsonlumber",
            "bowmanconsulting",
            "safecu",
            "logrhythm",
            "tuv",
            "hargray",
            "liveparallel",
            "ultragenyx",
            "ips",
            "knipper",
            "connectiverx",
            "nct911",
            "tcco",
            "gonzaba",
            "cnb",
            "friendshipvillageaz",
            "threerivershealth",
            "aaalife",
            "eulerhermes",
            "responsiveed",
            "ameristar",
            "ddn",
            "ecoatm",
            "granicus",
            "northstarcasinoresort",
            "trailappliances",
            "umlaut",
            "starspotlight",
            "afcompanies",
            "nanthealth",
            "newscycle",
            "unified",
            "aplusfcu",
            "carolinameadows",
            "germania",
            "promethean",
            "slippercafe",
            "apmortgage",
            "alwayshighfiving",
            "ims",
            "reprisedigital",
            "edfinancial",
            "hctec",
            "abrigo",
            "bergankdv",
            "fleetlanding",
            "orasure",
            "cambridgesavings",
            "fidelity",
            "47brand",
            "amig",
            "astronovainc",
            "beaumont",
            "gucu",
            "impactrto",
            "totalcard",
            "amica",
            "mctx",
            "prominence",
            "afcu",
            "hawaiiusafcu",
            "manntheatresmn",
            "tinder",
            "axiapillarpoints",
            "iqcu",
            "phillipsedison",
            "rogersinsurance",
            "beachbody",
            "metrocu",
            "allhealthnetwork",
            "fexco",
            "novaspect",
            "snaps",
            "pieper",
            "ampagency",
            "childnet",
            "continuumgroup",
            "efinancial",
            "nsc",
            "rauschcoleman",
            "zego",
            "dealeron",
            "fremont",
            "careerstaff",
            "essentra",
            "manhattanmotorcars",
            "actega",
            "mygenfcu",
            "withillinois",
            "baxterwoodman",
            "greatlakes",
            "ktbo",
            "mavs",
            "optanix",
            "razorfishhealth",
            "seastheday",
            "goamplify",
            "fbt",
            "ologybio",
            "braination",
            "catalystcorp",
            "westernbanks",
            "sunsetimports",
            "sbdanbury",
            "hudsonyardsexperiences",
            "lopa",
            "saatchix",
            "compeat",
            "inception",
            "ourhealth",
            "sagicor",
            "scefcu",
            "thestatebank",
            "tpc",
            "redw",
            "sfcu",
            "gable",
            "unitedaccess",
            "seguetech",
            "hsb",
            "lakeerieelectric",
            "cantatahealth",
            "republicwireless",
            "tmlt",
            "tompkinsinc",
            "woodhuston",
            "qandf",
            "tucsonfcu",
            "azuracu",
            "ffcu",
            "granite",
            "houstonretina",
            "austinretina",
            "hni",
            "locknet",
            "pearson",
            "santen",
            "dcf",
            "car2go",
            "happyfamily",
            "capitolservices",
            "hakco",
            "mva",
            "nvdonor",
            "vmsbiomarketing",
            "openeye",
            "ddbhealth",
            "quapawcasino",
            "champ",
            "cobbtechnologies",
            "colorado",
            "sdplus",
            "dropoff",
            "openskycorp",
            "equilend",
            "alliancecu",
            "dbb",
            "primewayfcu",
            "gsi",
            "nashvillevetspecialists",
            "augeofi",
            "bcirewards",
            "jordan-cu",
            "offenderwatch",
            "agtc",
            "arborpharma",
            "bbbsu",
            "bobmoore",
            "boothmachineryinc",
            "edops",
            "firstbankweb",
            "networkingresults",
            "onecu",
            "onedoor",
            "payrollnetwork",
            "pinalcountyfcu",
            "plus3it",
            "rbank",
            "reliabilityfirst",
            "rivervalleycu",
            "theabr",
            "unbanking",
            "uslacrosse",
            "xmc",
            "plr",
            "ggrmlawfirm",
            "camico",
            "kozma",
            "yourencore",
            "poopourri",
            "stl",
            "alliant",
            "stjeanscu",
            "cisnet",
            "comchoicecu",
            "leaveyourmark",
            "turnerconstructionnorcal",
            "motivateco",
            "iqt",
            "kia",
            "applefcu",
            "corbuspharma"
            ]}
    }
}, {
    $lookup: {
        from: 'groups',
        localField: '_id',
        foreignField: 'group_type_id',
        as: 'groups'
    }
}, {
    $project: {
        _id: 0,
        group_type_name: "$name",
        company_name: {$arrayElemAt: ["$companies.name", 0]},
        subdomain: {$arrayElemAt: ["$companies.subdomain", 0]},
        company_country:{ $ifNull: [{$arrayElemAt :["$companies.contact_address.country",0]},"null"]},
        count_of_GROUPS: {$size: "$groups"},
        GROUPS: "$groups.name"
    }
}
]
).toArray()
